package org.teals.magpie;

// STUDENTS - DO NOT EDIT THIS FILE
// you should be editing Magpie 2, 3, 4, or 5 
// depending on which part of the project you are on

// (we'll discuss in a later chapter what an interface is and why we need one here)
public interface Magpie {

	public String getResponse(String statement);
	public String getGreeting();

}
